### PR TITLE
The RunNotebook job throws a 'NotFound' error instead of 'RequestExecutionFailed'

### PR DESCRIPTION
**Pull request by jacobericson**
When querying the API for a "Pipeline" job too quickly after the execute call, the endpoint throws a "RequestExecutionFailed" error. When querying the API for a "RunNotebook" job, it throws an explicit "NotFound" error. This adjusts the retry logic to handle both of these errors so Airflow won't wrongly assume a "RunNotebook" job failed.

### CODE REVIEW

**Comment by ambika-garg** [comment]
Hi @jacobericson, thanks for the PR. 
Could you assist me in reproducing the issue?

**Comment by jacobericson** [comment]
I don't know the exact reasoning, but I didn't encounter this issue when I was using a small 1-2 cell testing notebook. When I actually went to run a larger 'real' notebook, that's when I started getting the same 'NotFound' error that was present on the Fabric Pipeline side. After 1-2 seconds of sleeping the API will typically start returning the status of the notebook run.

Ideally the Fabric 'Pipeline' job endpoint would return the same 'NotFound' error as the 'RunNotebook', but it looks like it's throwing an unhandled exception. I didn't want to rely on parsing failureReason.message to look for 'NotFound' and that's why I decided to apply the logic to the 'RequestExecutionFailed' error until we got a valid response. I've included logs for what I'm seeing in Airflow for both of the 'NotFound' exceptions below.

jobType: Pipeline
```
{
   "id":"<id>",
   "itemId":"<itemId>",
   "jobType":"Pipeline",
   "invokeType":"Manual",
   "status":"Failed",
   "failureReason":{
      "requestId":"<requestId>",
      "errorCode":"RequestExecutionFailed",
      "message":"ErrorResponseException while getting the Pipeline run status. [Exception: Microsoft.Di.AdfPartnerResourceprovider.Models.ErrorResponseException: Operation returned an invalid status code 'NotFound'\r\n   at Microsoft.Di.AdfPartnerResourceprovider.PipelineRunsOperations.<GetWithHttpMessagesAsync>d__6.MoveNext() in C:\\__w\\1\\s\\Core\\Microsoft.Di.AdfPartnerResourceProvider\\GeneratedSdk\\PipelineRunsOperations.cs:line 371\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Di.Service.WorkloadIntegration.Artifact.JobHandlers.PipelineArtifactJobHandler.<GetArtifactJobInstanceStatusAsync>d__4.MoveNext() in C:\\__w\\1\\s\\Service\\Microsoft.Di.Service\\WorkloadIntegration\\Artifact\\JobHandlers\\PipelineArtifactJobHandler.cs:line 119\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Di.Service.WorkloadIntegration.Artifact.JobHandlers.DiArtifactJobHandler.<GetArtifactJobInstanceStatusAsync>d__3.MoveNext() in C:\\__w\\1\\s\\Service\\Microsoft.Di.Service\\WorkloadIntegration\\Artifact\\JobHandlers\\DiArtifactJobHandler.cs:line 97]"
   },
   "rootActivityId":"<rootActivityId>",
   "startTimeUtc":"2024-08-15T23:25:36.3733333",
   "endTimeUtc":"None"
}
```

jobType: RunNotebook
```
{
   "id":"<id>",
   "itemId":"<itemId>",
   "jobType":"RunNotebook",
   "invokeType":"Manual",
   "status":"Failed",
   "failureReason":{
      "requestId":"<requestId>",
      "errorCode":"NotFound",
      "message":"No notebook execution state found in database for the runId - <id>"
   },
   "rootActivityId":"<rootActivityId>",
   "startTimeUtc":"2024-08-15T23:22:50.7266667",
   "endTimeUtc":"None"
}
```

**Comment by ambika-garg** [comment]
Could you add me as a collaborator on this PR?
We can work on this together to ensure all cases are covered.
I attempted to recreate the issue multiple times and was only able to mitigate it once.

Were you able to test your changes locally? Did you encounter any other error codes?

**Comment by jacobericson** [comment]
Added you!

The two error codes I put above were the only ones I encountered. I'm hoping those are the only two thrown when a premature API request for status is made, but maybe you have some more knowledge in regards to this. As is, neither of these errors are in the [docs](https://learn.microsoft.com/en-us/rest/api/fabric/core/job-scheduler/run-on-demand-item-job?tabs=HTTP) for the relevant endpoint.

A possible contributing factor is the notebook job that I'm running does import other notebooks as well, that may be the reason that I'm seeing it more frequently. I will say it is a consistent issue in the notebook I'm trying to execute from Airflow. I kicked off about 40 'RunNotebook' jobs earlier today, and in each of them I'm seeing `"errorCode":"NotFound"` on the initial API request.

**Comment by ambika-garg** [comment]
Hey @jacobericson,

I’ve made a few modifications by moving the retry mechanism into the function itself, rather than keeping it in the operator class. This change helps avoid redundant code in every function call.

Once this PR is merged, I plan to extend the retry mechanism to all relevant function calls.

**Comment by ambika-garg** [comment]
Hey @jacobericson, I have merged the retry mechanism in the main branch. Please feel free to test it.

**Comment by jacobericson** [comment]
@ambika-garg I was able to look at your changes and overall I think it's definitely a cleaner way of implementing the wait. My only issue is that it seems like your using tenacity's retry functionality, but not importing it in the file causing errors. I think you'd need something like: d8783a0872fdec11843051d22dfc6e6b5e695740 as well as adding the tenacity library as a project dependency.

**Comment by ambika-garg** [comment]
Oh man, Thanks for pointing it out. mistakenly I missed this commit on my local repo.

**Comment by ambika-garg** [comment]
Hi @jacobericson, I think this PR is ready to merge? Thoughts?

**Comment by rfsouth-ersm** [comment]
I also discovered this bug, then saw this PR.
Since there are no reviewers assigned I wanted to add that I've read through the changes, and agree that the PR looks ready to merge.

Kudos for writing this plugin! Was about to start writing one myself earlier this week, but then discovered this - so saved me/us a lot of time! 😸

**Comment by ambika-garg** [comment]
Hey @rfsouth-ersm, Thanks for reviewing the PR! I’m really happy that this plugin saved you some time—it's always great to know that the work benefits others in the community. 😸

I'll be merging the PR shortly.

Kind regards, 
Ambika

**Comment by ambika-garg** [comment]
Hey @jacobericson , @rfsouth-ersm , I'm closing this PR as I made these changes in the main repo already, please free to use retry mechanism from main branch.

**Pull request closed without merging**
